# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'Monitor'

# remote_read:
#   - url: "http://prometheus1:9094/api/v1/read"

scrape_configs:
- job_name: 'HostsMetrics'
  dns_sd_configs:
  - names:
    - node-exporter
    refresh_interval: 15s
    type: A
    port: 9100

- job_name: 'Prometheus'
  static_configs:
    - targets:
      - '127.0.0.1:9090'

- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
    - targets: ['cadvisor:8080']


- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - https://api.allianz.de/kraft2prod    # Target to probe with http.
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115  # Blackbox exporter.# my global config

- job_name: 'grafana45'
  scrape_interval: 15s
  metrics_path: /metrics
  static_configs:
    - targets: ['grafana5:3000']